### ISSUE TITLE
kitty config dir

### ISSUE THREAD

**Issue by tie** [Jomik/kitty-completions#1]
Actually,  [`$HOME/.config/kitty/kitty.conf`](https://github.com/Jomik/kitty-completions/blob/b32083cb233f9472cefa8ddd97113c78a4e7d6da/completions/kitty.fish#L59) is not the only possible config path, even though it's very common on Linux systems.

From [kitty/constants.py](https://github.com/kovidgoyal/kitty/blob/51b6b325b903d1fb880eb1111f4a79fa8527f2ae/kitty/constants.py#L26-L33):
```python
def _get_config_dir():
    if 'KITTY_CONFIG_DIRECTORY' in os.environ:
        return os.path.abspath(os.path.expanduser(os.environ['KITTY_CONFIG_DIRECTORY']))

    candidate = os.path.abspath(os.path.expanduser(os.environ.get('XDG_CONFIG_HOME') or ('~/Library/Preferences' if is_macos else '~/.config')))
    ans = os.path.join(candidate, appname)
    os.makedirs(ans, exist_ok=True)
    return ans


config_dir = _get_config_dir()
del _get_config_dir
defconf = os.path.join(config_dir, 'kitty.conf')
```

**Comment by Jomik** [comment]
Yeah, that is correct. This was mostly initial setup. - I was considering displaying the current values of each config option as well, as they are present anyway.

**Comment by Jomik** [comment]
Not sure how to test if we're in macos.

**Comment by tie** [comment]
@Jomik
> Not sure how to test if we're in macos.

Have a look at [__fish_complete_zfs_mountpoint_properties.fish](https://github.com/fish-shell/fish-shell/blob/dcf9ce6fc5ba802876b3bdda44d3563f2ac51e9f/share/functions/__fish_complete_zfs_mountpoint_properties.fish#L2-L15)

And I'd rather test if variable is set becase `/kitty.conf`, `/kitty/kitty.conf` and `/.config/kitty/kitty.conf` files may exist.

```fish
 function __kitty_config
  set -l candidate ~/.config/kitty
  if set -q KITTY_CONFIG_DIRECTORY
    set candidate "$KITTY_CONFIG_DIRECTORY"
  else if set -q XDG_CONFIG_HOME
    set candidate "$XDG_CONFIG_HOME"/kitty
  else if test (uname) = "Darwin"
    set candidate ~/Library/Preferences
  end
  
  if test -e $candidate/kitty.conf
    cat $candidate/kitty.conf | grep -P "^[^#]" | grep -P "^(?!map)" | awk '{print $1"\t"$2}'
  end
end

```

**Comment by Jomik** [comment]
Much better, and yeah, I just couldn't remember how to check if a variable was set :smile: feel free to do a PR, or I will make the change tomorrow
